/**
 * GoetheReady 词汇批量生成脚本
 * 
 * 使用方法：
 * 1. 把这个文件放到项目根目录（和 package.json 同一层）
 * 2. 确保 .env 里有 VITE_OPENAI_API_KEY=你的key
 * 3. 在终端运行：node generate_vocab.js
 * 4. 等待完成后，src/data/vocab_complete.json 就是完整词库
 * 
 * 预计时间：约 30-40 分钟
 * 预计费用：约 $1-2（GPT-4o-mini）
 * 断点续传：中途断了重新运行会从上次继续
 */

import fs from 'fs';
import path from 'path';

const API_KEY = process.env.VITE_OPENAI_API_KEY;
if (!API_KEY) {
  console.error('❌ 找不到 VITE_OPENAI_API_KEY，请检查 .env 文件');
  process.exit(1);
}

// 从歌德官方B1词汇表提取的 2704 个词
const WORD_LIST = [
  "abschreiben",
  "das Abitur",
  "ablehnen",
  "abmachen",
  "abnehmen",
  "abonnieren",
  "das Abonnement",
  "absagen",
  "der Abschluss",
  "der Abschnitt",
  "der Absender",
  "die Absicht",
  "absolut",
  "abstimmen",
  "die Abteilung",
  "der Abwart",
  "abwärts",
  "abwaschen",
  "abwesend",
  "achten",
  "abbiegen",
  "die Abbildung",
  "das Abenteuer",
  "abfahren",
  "die Abfahrt",
  "der Abfall",
  "der Abfalleimer",
  "abgeben",
  "abhängen",
  "abhängig",
  "abheben",
  "abholen",
  "alltäglich",
  "das Alphabet",
  "als",
  "also",
  "alt",
  "das Alter",
  "das Altenheim",
  "das Altersheim",
  "alternativ",
  "die Alternative",
  "die Ampel",
  "das Amt",
  "sich amüsieren",
  "analysieren",
  "anbieten",
  "die Adresse",
  "ähnlich",
  "die Ahnung",
  "die Aktion",
  "aktiv",
  "die Aktivität",
  "aktuell",
  "akzeptieren",
  "der Alarm",
  "der Alkohol",
  "all-",
  "allein",
  "aller-",
  "allerdings",
  "allgemein",
  "der Alltag",
  "die Angst",
  "ängstlich",
  "anhaben",
  "anklicken",
  "ankommen",
  "die Ankunft",
  "ankündigen",
  "die Anlage",
  "die Anleitung",
  "anmelden",
  "die Anmeldung",
  "annehmen",
  "die Annonce",
  "die Anrede",
  "anrufen",
  "der Anruf",
  "der Anrufbeantworter",
  "die Ansage",
  "der Anbieter",
  "das Angebot",
  "ander-",
  "andererseits",
  "ändern",
  "die Änderung",
  "anders",
  "anerkennen",
  "anfangen",
  "der Anfang",
  "anfangs",
  "angeben",
  "die Angabe",
  "der Angehörige",
  "angenehm",
  "der Anwalt",
  "anzeigen",
  "die Anzeige",
  "der Anzug",
  "das Apartment",
  "der Apfel",
  "die Apotheke",
  "der Apparat",
  "der Appetit",
  "die Aprikose",
  "arbeiten",
  "die Arbeit",
  "der Arbeiter",
  "die Arbeitserlaubnis",
  "arbeitslos",
  "die Arbeitslosigkeit",
  "der Arbeitsplatz",
  "die Arbeitsstelle",
  "anschaffen",
  "anschließen",
  "der Anschluss",
  "anschnallen",
  "ansehen",
  "ansprechen",
  "der Anspruch",
  "anstellen",
  "der Angestellte",
  "sich anstrengen",
  "anstrengend",
  "der Antrag",
  "anwenden",
  "anwesend",
  "antworten",
  "die Antwort",
  "der Aufenthalt",
  "auffallen",
  "auffordern",
  "die Aufforderung",
  "aufführen",
  "die Aufgabe",
  "aufgeben",
  "aufhalten",
  "aufheben",
  "aufhören",
  "aufladen",
  "auflösen",
  "aufmerksam",
  "aufnehmen",
  "die Aufnahme",
  "der Architekt",
  "der Ärger",
  "ärgerlich",
  "arm",
  "der Arm",
  "die Art",
  "der Artikel",
  "der Arzt",
  "das Asyl",
  "atmen",
  "der Atem",
  "auf",
  "die Ausbildung",
  "ausgebildet",
  "ausdrucken",
  "der Ausdruck",
  "auseinander",
  "die Ausfahrt",
  "ausfallen",
  "der Ausflug",
  "ausfüllen",
  "die Ausgabe",
  "der Ausgang",
  "ausgeben",
  "ausgehen",
  "ausgezeichnet",
  "die Aushilfe",
  "die Auskunft",
  "das Ausland",
  "aufpassen",
  "aufräumen",
  "aufregen",
  "aufstehen",
  "der Auftrag",
  "auftreten",
  "der Auftritt",
  "aufwachen",
  "aufwärts",
  "der Aufzug",
  "das Auge",
  "der Augenblick",
  "aus",
  "die Aussicht",
  "aussprechen",
  "die Aussprache",
  "ausstellen",
  "die Ausstellung",
  "auswählen",
  "die Auswahl",
  "der Ausweis",
  "ausziehen",
  "das Auto",
  "die Autobahn",
  "der Automat",
  "automatisch",
  "der Autor",
  "der Ausländer",
  "ausmachen",
  "die Ausnahme",
  "ausreichen",
  "ausreichend",
  "ausrichten",
  "ausschließen",
  "ausschließlich",
  "aussehen",
  "außen",
  "außerhalb",
  "äußerlich",
  "außer",
  "außerdem",
  "die Bar",
  "bar",
  "das Bargeld",
  "der Bart",
  "der Basketball",
  "basteln",
  "die Batterie",
  "der Bauch",
  "bauen",
  "der Bau",
  "die Baustelle",
  "der Bauer",
  "der Baum",
  "beachten",
  "der Beamte",
  "beantragen",
  "beantworten",
  "sich bedanken",
  "der Bedarf",
  "bedeuten",
  "die Bedeutung",
  "backen",
  "die Bäckerei",
  "baden",
  "das Bad",
  "die Badewanne",
  "die Bahn",
  "die Straßenbahn",
  "die U-Bahn",
  "der Bahnhof",
  "der Bahnsteig",
  "bald",
  "der Balkon",
  "der Ball",
  "das Ballett",
  "die Banane",
  "die Bank",
  "der Bancomat",
  "die Bankleitzahl",
  "die Bankomat-Karte",
  "behaupten",
  "behindern",
  "die Behörde",
  "bei",
  "beid-",
  "das Bein",
  "beinahe",
  "das Beispiel",
  "beißen",
  "der Beitrag",
  "bekannt",
  "der Bekannte",
  "bekommen",
  "bedienen",
  "die Bedienungsanleitung",
  "die Bedingung",
  "sich beeilen",
  "beenden",
  "sich befinden",
  "befreit",
  "befriedigend",
  "begegnen",
  "begeistert",
  "beginnen",
  "der Beginn",
  "begleiten",
  "begrenzt",
  "begründen",
  "die Begründung",
  "begrüßen",
  "behalten",
  "behandeln",
  "berichten",
  "der Bericht",
  "der Beruf",
  "beruflich",
  "berufstätig",
  "beruhigen",
  "berühmt",
  "beschädigen",
  "beschäftigen",
  "die Beschäftigung",
  "der Bescheid",
  "beschließen",
  "beschränken",
  "beschreiben",
  "die Beschreibung",
  "sich beschweren",
  "der Beleg",
  "beleidigen",
  "beliebt",
  "bemerken",
  "sich bemühen",
  "benötigen",
  "benutzen",
  "das Benzin",
  "beobachten",
  "bequem",
  "beraten",
  "die Beratung",
  "berechnen",
  "der Bereich",
  "bereit",
  "bereits",
  "der Berg",
  "sich beteiligen",
  "der Betrag",
  "betreuen",
  "der Betreuer",
  "die Betreuung",
  "der Betrieb",
  "der Betriebsrat",
  "betrügen",
  "betrunken",
  "das Bett",
  "die Bevölkerung",
  "bevor",
  "bewegen",
  "die Bewegung",
  "beweisen",
  "der Beweis",
  "sich bewerben",
  "die Bewerbung",
  "besetzen",
  "besichtigen",
  "besonder-",
  "besonders",
  "besorgen",
  "besprechen",
  "die Besprechung",
  "die Besserung",
  "bestätigen",
  "die Bestätigung",
  "bestehen",
  "bestellen",
  "bestimmt",
  "bestrafen",
  "besuchen",
  "der Besuch",
  "die Bitte",
  "bitter",
  "blass",
  "das Blatt",
  "bleiben",
  "der Bleistift",
  "der Blick",
  "blind",
  "blitzen",
  "der Blitz",
  "blond",
  "bloß",
  "blühen",
  "die Blume",
  "die Bluse",
  "bluten",
  "das Blut",
  "der Bewohner",
  "bezahlen",
  "die Beziehung",
  "die Bibliothek",
  "das Bier",
  "bieten",
  "das Bild",
  "der Bildschirm",
  "das Billett",
  "billig",
  "die Biologie",
  "die Birne",
  "bis",
  "bisher",
  "bitten",
  "der Brief",
  "der Briefkasten",
  "die Briefmarke",
  "der Briefträger",
  "der Briefumschlag",
  "die Brieftasche",
  "die Brille",
  "bringen",
  "die Broschüre",
  "das Brot",
  "das Brötchen",
  "das Brötli",
  "die Brücke",
  "der Bruder",
  "die Brust",
  "der Bub",
  "das Buch",
  "die Buchhandlung",
  "buchen",
  "der Boden",
  "der Bogen",
  "die Bohne",
  "das Boot",
  "die Botschaft",
  "böse",
  "braten",
  "der Braten",
  "brauchen",
  "brechen",
  "breit",
  "die Breite",
  "bremsen",
  "die Bremse",
  "brennen",
  "die Couch",
  "die Creme",
  "der Cousin",
  "das Couvert",
  "dabei",
  "das Dach",
  "dafür",
  "dagegen",
  "daher",
  "dahin",
  "buchstabieren",
  "der Buchstabe",
  "die Büchse",
  "das Buffet",
  "die Bühne",
  "bunt",
  "die Burg",
  "der Bürger",
  "das Büro",
  "die Bürste",
  "die Zahnbürste",
  "der Bus",
  "die Butter",
  "das Caf",
  "die Cafeteria",
  "die Chance",
  "der Chef",
  "der Coiffeur",
  "dauern",
  "die Dauer",
  "dauernd",
  "die Decke",
  "dekorieren",
  "denken",
  "der Gedanke",
  "das Denkmal",
  "denn",
  "derselbe",
  "deshalb",
  "das Dessert",
  "deswegen",
  "damals",
  "die Dame",
  "damit",
  "danach",
  "daneben",
  "danken",
  "der Dank",
  "dankbar",
  "danke",
  "dann",
  "darstellen",
  "die Darstellung",
  "dass",
  "die Datei",
  "das Datum",
  "die Daten",
  "diskutieren",
  "die Diskussion",
  "die Distanz",
  "doch",
  "der Doktor",
  "das Dokument",
  "donnern",
  "der Donner",
  "doppelt",
  "das Dorf",
  "dort",
  "dorthin",
  "die Dose",
  "draußen",
  "der Dreck",
  "das Detail",
  "deutlich",
  "die Diät",
  "der Dialekt",
  "der Dialog",
  "dicht",
  "dick",
  "der Dieb",
  "dienen",
  "der Dienst",
  "dies-",
  "diesmal",
  "digital",
  "das Ding",
  "das Diplom",
  "direkt",
  "der Direktor",
  "die Diskothek",
  "durcheinander",
  "die Durchsage",
  "der Durchschnitt",
  "durchschnittlich",
  "dürfen",
  "der Durst",
  "durstig",
  "die Dusche",
  "duzen",
  "eben",
  "ebenfalls",
  "ebenso",
  "drehen",
  "dringend",
  "drin",
  "die Droge",
  "die Drogerie",
  "drüben",
  "drucken",
  "der Drucker",
  "drücken",
  "der Druck",
  "dumm",
  "dunkel",
  "dünn",
  "durch",
  "eilen",
  "die Eile",
  "ein-",
  "die Einbahnstraße",
  "einbrechen",
  "der Einbrecher",
  "der Einbruch",
  "eindeutig",
  "der Eindruck",
  "einerseits",
  "einfach",
  "die Einfahrt",
  "einfallen",
  "der Einfall",
  "der Einfluss",
  "echt",
  "die Ecke",
  "das Eck",
  "eckig",
  "egal",
  "die Ehe",
  "die Ehefrau",
  "das Ehepaar",
  "eher",
  "ehrlich",
  "das Ei",
  "eigen-",
  "eigentlich",
  "sich eignen",
  "die Einnahme",
  "einpacken",
  "einrichten",
  "die Einrichtung",
  "einsam",
  "einschalten",
  "einschließlich",
  "das Einschreiben",
  "einsetzen",
  "einsteigen",
  "einstellen",
  "eintragen",
  "eintreten",
  "der Eintritt",
  "einverstanden",
  "der Einwohner",
  "beeinflussen",
  "einfügen",
  "einführen",
  "die Einführung",
  "der Eingang",
  "einheitlich",
  "einig-",
  "sich einigen",
  "einkaufen",
  "der Einkauf",
  "das Einkommen",
  "einladen",
  "die Einladung",
  "einmal",
  "einnehmen",
  "enden",
  "das Ende",
  "endgültig",
  "endlich",
  "die Energie",
  "eng",
  "der Enkel",
  "entdecken",
  "entfernen",
  "die Entfernung",
  "entgegenkommen",
  "enthalten",
  "entlang",
  "entlassen",
  "die Entlassung",
  "einzahlen",
  "die Einzahlung",
  "einzeln",
  "die Einzelheit",
  "einzig-",
  "einziehen",
  "das Eis",
  "die Eisenbahn",
  "elegant",
  "elektrisch",
  "elektronisch",
  "die Eltern",
  "empfangen",
  "der Empfang",
  "der Empfänger",
  "empfehlen",
  "die Empfehlung",
  "der Erdapfel",
  "das Erdgeschoss",
  "das Ereignis",
  "sich ereignen",
  "erfahren",
  "die Erfahrung",
  "erfinden",
  "die Erfindung",
  "der Erfolg",
  "erfolgreich",
  "erforderlich",
  "erfordern",
  "erfüllen",
  "ergänzen",
  "das Ergebnis",
  "erhalten",
  "erhöhen",
  "entscheiden",
  "die Entscheidung",
  "unentschieden",
  "sich entschließen",
  "entschlossen",
  "entschuldigen",
  "die Entschuldigung",
  "entsorgen",
  "entspannend",
  "entstehen",
  "enttäuschen",
  "die Enttäuschung",
  "entwickeln",
  "die Entwicklung",
  "die Erde",
  "erledigen",
  "erleichtern",
  "die Ermäßigung",
  "ernähren",
  "die Ernährung",
  "ernst",
  "ernsthaft",
  "die Ernte",
  "eröffnen",
  "die Eröffnung",
  "erreichen",
  "erschöpft",
  "erschrecken",
  "ersetzen",
  "der Ersatz",
  "erst",
  "die Erhöhung",
  "sich erholen",
  "die Erholung",
  "erinnern",
  "die Erinnerung",
  "sich erkälten",
  "erkältet",
  "die Erkältung",
  "erkennen",
  "erklären",
  "die Erklärung",
  "sich erkundigen",
  "erlauben",
  "die Erlaubnis",
  "erleben",
  "das Erlebnis",
  "etwas",
  "eventuell",
  "ewig",
  "der Experte",
  "der Export",
  "extra",
  "extrem",
  "die Fabrik",
  "das Fach",
  "der Fachmann",
  "die Fachleute",
  "die Fähigkeit",
  "fahren",
  "die Fähre",
  "erst-",
  "erstellen",
  "erwachsen",
  "der Erwachsene",
  "erwarten",
  "erzählen",
  "die Erzählung",
  "erziehen",
  "die Erziehung",
  "essen",
  "das Essen",
  "der Essig",
  "die Etage",
  "etwa",
  "fantastisch",
  "die Farbe",
  "farbig",
  "das Faschierte",
  "der Fasching",
  "die Fasnacht",
  "fassen",
  "fast",
  "faul",
  "faulenzen",
  "der Fauteuil",
  "fehlen",
  "der Fehler",
  "feiern",
  "die Feier",
  "der Feierabend",
  "der Feiertag",
  "das Feld",
  "das Fenster",
  "die Fahrbahn",
  "der Fahrer",
  "die Fahrkarte",
  "der Fahrplan",
  "das Fahrrad",
  "das Fahrzeug",
  "fair",
  "der Faktor",
  "der Fall",
  "fallen",
  "fällig",
  "falls",
  "falsch",
  "die Familie",
  "der Familienstand",
  "fangen",
  "die Fantasie",
  "das Fett",
  "feucht",
  "das Feuer",
  "das Feuerzeug",
  "die Feuerwehr",
  "das Fieber",
  "die Figur",
  "der Film",
  "finanzieren",
  "finanziell",
  "finden",
  "der Finger",
  "die Firma",
  "flach",
  "die Fläche",
  "die Flasche",
  "der Fleck",
  "das Fleisch",
  "der Fleischhauer",
  "fleißig",
  "die Ferien",
  "die Fernbedienung",
  "fernsehen",
  "das Fernsehen",
  "der Fernseher",
  "fertig",
  "fest",
  "das Fest",
  "die Festplatte",
  "festhalten",
  "festlegen",
  "festsetzen",
  "feststehen",
  "feststellen",
  "fett",
  "das Formular",
  "die Forschung",
  "die Fortbildung",
  "der Fortschritt",
  "fortsetzen",
  "die Fortsetzung",
  "das Forum",
  "fotografieren",
  "das Foto",
  "der Fotoapparat",
  "der Fotograf",
  "die Fotografie",
  "fragen",
  "die Frage",
  "die Frau",
  "frech",
  "frei",
  "die Freiheit",
  "die Freizeit",
  "flexibel",
  "fliegen",
  "fliehen",
  "die Flucht",
  "fließen",
  "fließend",
  "der Flohmarkt",
  "die Flöte",
  "der Flug",
  "der Flughafen",
  "das Flugzeug",
  "der Flur",
  "der Fluss",
  "die Flüssigkeit",
  "folgen",
  "die Folge",
  "folgend",
  "fordern",
  "die Forderung",
  "fördern",
  "die Förderung",
  "die Form",
  "frühstücken",
  "das Frühstück",
  "fühlen",
  "führen",
  "der Führerausweis",
  "der Führerschein",
  "die Führung",
  "das Fundbüro",
  "funktionieren",
  "für",
  "freiwillig",
  "fremd",
  "fressen",
  "sich freuen",
  "die Freude",
  "der Freund",
  "freundlich",
  "die Freundschaft",
  "der Friede",
  "frieren",
  "frisch",
  "der Friseur",
  "die Frisur",
  "die Frist",
  "froh",
  "fröhlich",
  "die Frucht",
  "früh",
  "der Garten",
  "das Gas",
  "der Gast",
  "das Gasthaus",
  "die Gaststätte",
  "das Gebäude",
  "geben",
  "das Gebäck",
  "das Gebiet",
  "das Gebirge",
  "gebrauchen",
  "die Gebrauchsanweisung",
  "die Gebühr",
  "die Geburt",
  "der Geburtstag",
  "das Gedicht",
  "die Geduld",
  "furchtbar",
  "der Fuß",
  "der Fußball",
  "der Fußgänger",
  "die Fußgängerzone",
  "füttern",
  "die Gabel",
  "die Galerie",
  "der Gang",
  "ganz",
  "gar",
  "die Garage",
  "garantieren",
  "die Garantie",
  "die Garderobe",
  "gegenüber",
  "das Gehalt",
  "das Geheimnis",
  "geheim",
  "gehen",
  "gehören",
  "der Gehsteig",
  "das Geld",
  "der Geldautomat",
  "die Geldbörse",
  "die Gelegenheit",
  "gelingen",
  "geehrt",
  "geeignet",
  "die Gefahr",
  "gefährlich",
  "gefallen",
  "sich etwas",
  "das Gefängnis",
  "das Gefühl",
  "gegen",
  "der Gegner",
  "die Gegend",
  "der Gegensatz",
  "der Gegenstand",
  "das Gegenteil",
  "das Gericht",
  "gering",
  "das Geschäft",
  "geschehen",
  "das Geschenk",
  "die Geschichte",
  "geschieden",
  "das Geschirr",
  "das Geschlecht",
  "der Geschmack",
  "die Geschwindigkeit",
  "die Geschwindigkeits-",
  "die Geschwister",
  "die Gesellschaft",
  "das Gesetz",
  "das Gesicht",
  "gelten",
  "gemeinsam",
  "die Gemeinschaft",
  "das Gemüse",
  "gemütlich",
  "genau",
  "genauso",
  "genehmigen",
  "die Generation",
  "genießen",
  "genug",
  "genügen",
  "das Gepäck",
  "gerade",
  "geradeaus",
  "das Gerät",
  "gerecht",
  "das Gewürz",
  "gießen",
  "das Gift",
  "giftig",
  "die Gitarre",
  "glatt",
  "glauben",
  "gleich",
  "gleichfalls",
  "gleichberechtigt",
  "gleichzeitig",
  "das Gleis",
  "das Glück",
  "glücklich",
  "der Glückwunsch",
  "das Gold",
  "gespannt",
  "das Gespräch",
  "gestern",
  "gesund",
  "die Gesundheit",
  "das Getränk",
  "die Gewalt",
  "die Gewerkschaft",
  "das Gewicht",
  "gewinnen",
  "der Gewinn",
  "das Gewissen",
  "das Gewitter",
  "gewöhnen",
  "die Gewohnheit",
  "gewohnt",
  "gewöhnlich",
  "gründlich",
  "das Grundstück",
  "die Gruppe",
  "grüßen",
  "der Gruß",
  "gucken",
  "gültig",
  "günstig",
  "gut",
  "die Gymnastik",
  "das Haar",
  "haben",
  "der Gott",
  "die Grafik",
  "das Gras",
  "gratulieren",
  "die Gratulation",
  "gratis",
  "greifen",
  "die Grenze",
  "grillen",
  "grillieren",
  "der Grill",
  "die Grippe",
  "groß",
  "die Größe",
  "gründen",
  "der Grund",
  "der Halt",
  "die Haltestelle",
  "der Hammer",
  "die Hand",
  "der Handwerker",
  "handeln",
  "der Handel",
  "der Händler",
  "das Handy",
  "hängen",
  "hart",
  "hassen",
  "hässlich",
  "häufig",
  "das Hackfleisch",
  "der Hafen",
  "hageln",
  "das Hähnchen",
  "halb",
  "die Halbpension",
  "halbtags",
  "die Hälfte",
  "die Halle",
  "das Hallenbad",
  "hallo",
  "der Hals",
  "halt",
  "haltbar",
  "halten",
  "die Heizung",
  "der Held",
  "helfen",
  "die Hilfe",
  "hell",
  "das Hemd",
  "das Hend",
  "heraus-",
  "die Herausforderung",
  "der Herd",
  "herein-",
  "die Herkunft",
  "der Herr",
  "herstellen",
  "der Hersteller",
  "herunter-",
  "der Hauptbahnhof",
  "das Haus",
  "die Hausaufgabe",
  "die Hausfrau",
  "der Haushalt",
  "der Hausmeister",
  "die Haut",
  "heben",
  "das Heft",
  "heim",
  "das Heim",
  "die Heimat",
  "heimlich",
  "das Heimweh",
  "heiraten",
  "heiß",
  "heißen",
  "heizen",
  "der Hinweise",
  "historisch",
  "die Hitze",
  "das Hobby",
  "hoch",
  "die Höhe",
  "hochladen",
  "höchstens",
  "die Hochzeit",
  "der Hof",
  "der Bauernhof",
  "hoffen",
  "hoffentlich",
  "die Hoffnung",
  "höflich",
  "holen",
  "das Holz",
  "der Honig",
  "hören",
  "das Herz",
  "heutig-",
  "hierher",
  "der Himmel",
  "hinten",
  "hinterlassen",
  "hinterher",
  "hinweisen",
  "immer",
  "der Import",
  "indem",
  "individuell",
  "die Industrie",
  "die Infektion",
  "informieren",
  "die Information",
  "der Ingenieur",
  "der Inhalt",
  "inklusive",
  "innen",
  "inner-",
  "innerhalb",
  "der Hörer",
  "die Hose",
  "das Hotel",
  "hübsch",
  "der Hügel",
  "der Humor",
  "der Hunger",
  "hungrig",
  "hupen",
  "husten",
  "der Husten",
  "der Hut",
  "die Hütte",
  "ideal",
  "die Idee",
  "illegal",
  "der Imbiss",
  "das Interview",
  "inzwischen",
  "irgendwann",
  "sich irren",
  "die Jacke",
  "die Jause",
  "die Jeans",
  "jeder",
  "die Insel",
  "das Inserat",
  "insgesamt",
  "installieren",
  "das Institut",
  "das Instrument",
  "integrieren",
  "die Integration",
  "intelligent",
  "die Intelligenz",
  "intensiv",
  "der Intensivkurs",
  "interessieren",
  "interessant",
  "das Interesse",
  "interessiert",
  "interkulturell",
  "international",
  "das Kabel",
  "die Kabine",
  "der Kaffee",
  "das Kaffeehaus",
  "der Kakao",
  "der Kalender",
  "kalt",
  "die Kälte",
  "die Kamera",
  "kämpfen",
  "der Kampf",
  "der Kanal",
  "der Kandidat",
  "die Kanne",
  "die Kantine",
  "das Kapitel",
  "jederzeit",
  "jedoch",
  "jemals",
  "jemand",
  "jetzt",
  "jeweils",
  "der Journalist",
  "die Jugend",
  "der Jugendliche",
  "die Jugendherberge",
  "jung",
  "der Junge",
  "der Käufer",
  "kaum",
  "kein-",
  "der Keller",
  "der Kellner",
  "kennen",
  "kennenlernen",
  "die Kenntnisse",
  "das Kennzeichen",
  "die Kerze",
  "die Kette",
  "das Kind",
  "der Kindergarten",
  "die Kindheit",
  "das Kino",
  "der Kiosk",
  "die Kirche",
  "kaputt",
  "kaputtgehen",
  "kaputtmachen",
  "der Karneval",
  "die Karotte",
  "die Karriere",
  "die Karte",
  "die Chipkarte",
  "die Kartoffel",
  "der Käse",
  "die Kasse",
  "die Kassette",
  "der Kasten",
  "der Katalog",
  "die Katastrophe",
  "der Kauf",
  "klingeln",
  "die Klingel",
  "klingen",
  "die Klinik",
  "klopfen",
  "der Kloß",
  "klug",
  "knapp",
  "die Kneipe",
  "das Knie",
  "der Knochen",
  "der Knödel",
  "der Knopf",
  "kochen",
  "der Koch",
  "der Koffer",
  "der Kollege",
  "die Kiste",
  "das Kissen",
  "klagen",
  "klappen",
  "klar",
  "klären",
  "klasse",
  "die Klasse",
  "die Klassenarbeit",
  "das Klavier",
  "kleben",
  "das Kleid",
  "die Kleidung",
  "klein",
  "klettern",
  "klicken",
  "der Klick",
  "das Klima",
  "die Klimaanlage",
  "das Konsulat",
  "konsumieren",
  "der Konsum",
  "der Kontakt",
  "das Konto",
  "das Girokonto",
  "kontrollieren",
  "die Kontrolle",
  "sich konzentrieren",
  "das Konzert",
  "der Kopf",
  "kopieren",
  "die Kopie",
  "der Kopierer",
  "der Körper",
  "körperlich",
  "korrekt",
  "der Korridor",
  "korrigieren",
  "komisch",
  "kommen",
  "die Kommunikation",
  "komplett",
  "kompliziert",
  "der Kompromiss",
  "die Konferenz",
  "die Konfitüre",
  "der Konflikt",
  "der König",
  "die Konkurrenz",
  "können",
  "der Kredit",
  "die Kreditkarte",
  "der Kreis",
  "das Kreuz",
  "die Kreuzung",
  "der Krieg",
  "kriegen",
  "der Krimi",
  "die Krise",
  "kritisieren",
  "die Kritik",
  "kritisch",
  "die Küche",
  "der Kuchen",
  "der Kugelschreiber",
  "der Kuli",
  "kühl",
  "der Kühlschrank",
  "kosten",
  "die Kosten",
  "kostenlos",
  "das Kostüm",
  "die Kraft",
  "kräftig",
  "das Kraftfahrzeug",
  "das Kraftwerk",
  "krank",
  "der Kranke",
  "das Krankenhaus",
  "die Krankenkasse",
  "der Krankenpfleger",
  "die Krankenschwester",
  "der Krankenwagen",
  "die Krankheit",
  "kreativ",
  "küssen",
  "der Kuss",
  "die Küste",
  "das Kuvert",
  "lächeln",
  "lachen",
  "der Laden",
  "die Lage",
  "das Lager",
  "die Lampe",
  "das Land",
  "die Landwirtschaft",
  "die Landschaft",
  "landen",
  "die Kultur",
  "kulturell",
  "sich kümmern",
  "der Kunde",
  "kündigen",
  "die Kündigung",
  "die Kunst",
  "der Künstler",
  "künstlich",
  "der Kunststoff",
  "der Kursleiter",
  "die Kurve",
  "kurz",
  "kürzlich",
  "laufen",
  "das Laufwerk",
  "die Laune",
  "laut",
  "der Lautsprecher",
  "lecker",
  "leben",
  "das Leben",
  "der Lebenslauf",
  "die Lebensmittel",
  "das Leder",
  "ledig",
  "leer",
  "legen",
  "die Lehre",
  "die Lehrstelle",
  "die Landung",
  "lang",
  "die Länge",
  "lange",
  "langsam",
  "längst",
  "langweilig",
  "sich langweilen",
  "die Langeweile",
  "der Lärm",
  "lassen",
  "der Laster",
  "der Lerner",
  "lesen",
  "der Leser",
  "letzt-",
  "die Leute",
  "das Lexikon",
  "das Licht",
  "lieben",
  "lieb",
  "die Liebe",
  "das Lied",
  "liefern",
  "die Lieferung",
  "liegen",
  "der Lehrer",
  "der Lehrling",
  "leicht",
  "leiden",
  "leider",
  "leihen",
  "leise",
  "leisten",
  "die Leistung",
  "leiten",
  "der Leiter",
  "die Leitung",
  "die Leiter",
  "lernen",
  "die Lösung",
  "die Luft",
  "lügen",
  "die Lüge",
  "die Lust",
  "lustig",
  "machen",
  "das Mädchen",
  "das Magazin",
  "der Magen",
  "mager",
  "die Mahlzeit",
  "die Mahnung",
  "der Lift",
  "die Limonade",
  "die Linie",
  "links",
  "link-",
  "die Lippe",
  "die Liste",
  "die Literatur",
  "loben",
  "das Loch",
  "locker",
  "der Löffel",
  "der Lohn",
  "sich lohnen",
  "das Lokal",
  "losfahren",
  "löschen",
  "lösen",
  "die Marmelade",
  "die Maschine",
  "das Material",
  "die Matura",
  "die Mauer",
  "maximal",
  "der Mechaniker",
  "die Medien",
  "das Medikament",
  "die Medizin",
  "das Meer",
  "das Mehl",
  "mehrere",
  "die Mehrheit",
  "die Mehrwertsteuer",
  "meinen",
  "mal",
  "das Mal",
  "malen",
  "der Maler",
  "man",
  "manch-",
  "manchmal",
  "der Mangel",
  "der Mann",
  "männlich",
  "die Mannschaft",
  "der Mantel",
  "die Mappe",
  "das Märchen",
  "die Margarine",
  "die Marille",
  "die Marke",
  "markieren",
  "der Markt",
  "messen",
  "das Messer",
  "das Metall",
  "die Methode",
  "die Metropole",
  "der Metzger",
  "mieten",
  "die Miete",
  "der Mieter",
  "der Migrant",
  "die Migration",
  "die Milch",
  "mild",
  "die Minderheit",
  "mindestens",
  "das Mineralwasser",
  "minimal",
  "mischen",
  "miss-",
  "meinetwegen",
  "die Meinung",
  "meist-",
  "der Meister",
  "melden",
  "die Meldung",
  "die Menge",
  "die Mensa",
  "der Mensch",
  "menschlich",
  "das Menü",
  "merken",
  "merkwürdig",
  "die Messe",
  "das Mobiltelefon",
  "die Mode",
  "das Modell",
  "modern",
  "mögen",
  "möglich",
  "die Möglichkeit",
  "möglichst",
  "die Möhre",
  "der Moment",
  "der Mond",
  "der Monitor",
  "der Motor",
  "das Motorrad",
  "müde",
  "die Mühe",
  "der Müll",
  "die Müllabfuhr",
  "mit",
  "der Mitarbeiter",
  "miteinander",
  "das Mitglied",
  "die Mitte",
  "mitteilen",
  "das Mittel",
  "mitten",
  "mittler-",
  "mittlerweile",
  "das Möbel",
  "möbliert",
  "möchten",
  "die Mobilbox",
  "die Mobilität",
  "nachdem",
  "nachdenken",
  "die Nachfrage",
  "nachher",
  "die Nachhilfe",
  "die Nachricht",
  "nachschlagen",
  "die Nachspeise",
  "der Nachteil",
  "der Nachwuchs",
  "die Nadel",
  "der Nagel",
  "die Nähe",
  "nähen",
  "sich nähern",
  "die Mülltonne",
  "der Mund",
  "mündlich",
  "die Münze",
  "das Museum",
  "die Musik",
  "musikalisch",
  "der Musiker",
  "der Muskel",
  "das Müesli",
  "müssen",
  "der Mut",
  "mutig",
  "die Mutter",
  "nach",
  "der Nachbar",
  "nein",
  "nennen",
  "der Nerv",
  "nervös",
  "nett",
  "das Netz",
  "das Netzwerk",
  "neu",
  "die Neuigkeit",
  "neugierig",
  "neulich",
  "die Nichte",
  "der Nichtraucher",
  "das Nahrungsmittel",
  "der Name",
  "der Familienname",
  "der Vorname",
  "nämlich",
  "die Nase",
  "nass",
  "die Natur",
  "natürlich",
  "der Nebel",
  "neblig",
  "neben",
  "nebenan",
  "nebenbei",
  "der Neffe",
  "negativ",
  "nehmen",
  "der Notruf",
  "die Note",
  "notieren",
  "nötig",
  "die Notiz",
  "notwendig",
  "die Nudel",
  "die Nummer",
  "nun",
  "nutzen",
  "nützen",
  "nützlich",
  "nichts",
  "nie",
  "niedrig",
  "niemand",
  "nirgends",
  "nirgendwo",
  "nochmals",
  "normal",
  "normalerweise",
  "der Notausgang",
  "der Notfall",
  "öffnen",
  "ohne",
  "das Ohr",
  "das Öl",
  "die Oma",
  "der Onkel",
  "der Opa",
  "die Oper",
  "operieren",
  "die Operation",
  "das Opfer",
  "optimistisch",
  "die Orange",
  "das Orchester",
  "oben",
  "ober-",
  "der Ober",
  "das Obst",
  "obwohl",
  "offen",
  "öffentlich",
  "die Öffentlichkeit",
  "veröffentlichen",
  "offenbar",
  "offiziell",
  "packen",
  "das Paket",
  "die Panne",
  "das Papier",
  "der Paradeiser",
  "parallel",
  "das Parfüm",
  "der Park",
  "parken",
  "der Partner",
  "die Party",
  "der Pass",
  "der Passagier",
  "passen",
  "passieren",
  "passiv",
  "ordentlich",
  "die Ordination",
  "ordnen",
  "der Ordner",
  "die Ordnung",
  "organisieren",
  "die Organisation",
  "das Original",
  "original",
  "der Ort",
  "der Vorort",
  "der Wohnort",
  "der Ozean",
  "das Paar",
  "der Pfeffer",
  "pflanzen",
  "die Pflanze",
  "das Pflaster",
  "die Pflaume",
  "pflegen",
  "der Pfleger",
  "die Pflicht",
  "die Phantasie",
  "das Picknick",
  "der Pilz",
  "die Pizza",
  "das Plakat",
  "planen",
  "der Plan",
  "die Planung",
  "das Plastik",
  "der Platz",
  "plötzlich",
  "der Patient",
  "pauschal",
  "die Pause",
  "das Pech",
  "peinlich",
  "die Pension",
  "der Pensionist",
  "per",
  "perfekt",
  "der Perron",
  "die Person",
  "persönlich",
  "die Personalien",
  "der Personenstand",
  "das Personal",
  "die Pfanne",
  "die Präsentation",
  "die Praxis",
  "der Preis",
  "preiswert",
  "die Presse",
  "prima",
  "privat",
  "pro",
  "probieren",
  "das Problem",
  "produzieren",
  "das Produkt",
  "die Produktion",
  "der Professor",
  "der Profi",
  "die Politik",
  "der Politiker",
  "politisch",
  "die Polizei",
  "der Polizist",
  "die Pommes",
  "populär",
  "das Portemonnaie",
  "die Portion",
  "positiv",
  "die Post",
  "die Postleitzahl",
  "der Pöstler",
  "das Poulet",
  "das Praktikum",
  "der Praktikant",
  "praktisch",
  "präsentieren",
  "das Quartier",
  "quer",
  "die Quittung",
  "das Quiz",
  "der Rabatt",
  "das Rad",
  "der Radfahrer",
  "das Radio",
  "der Rand",
  "der Rasen",
  "raten",
  "der Rat",
  "das Rätsel",
  "das Rathaus",
  "rauchen",
  "der Profisportler",
  "das Programm",
  "das Projekt",
  "der Prospekt",
  "protestieren",
  "der Protest",
  "der Prozess",
  "prüfen",
  "die Prüfung",
  "das Publikum",
  "der Pullover",
  "der Punkt",
  "pünktlich",
  "die Puppe",
  "putzen",
  "die Qualifikation",
  "die Qualität",
  "rechtzeitig",
  "reden",
  "die Rede",
  "reduzieren",
  "das Referat",
  "die Reform",
  "das Regal",
  "die Regel",
  "regelmäßig",
  "regeln",
  "regnen",
  "der Regen",
  "die Region",
  "regional",
  "reich",
  "reichen",
  "reif",
  "der Reifen",
  "die Reihe",
  "der Raucher",
  "der Raum",
  "reagieren",
  "die Reaktion",
  "realisieren",
  "die Realität",
  "realistisch",
  "die Recherche",
  "rechnen",
  "der Rechner",
  "die Rechnung",
  "das Recht",
  "rechtlich",
  "recht",
  "rechts",
  "recht-",
  "die Reparatur",
  "die Reportage",
  "der Reporter",
  "reservieren",
  "die Reservierung",
  "der Respekt",
  "der Rest",
  "das Restaurant",
  "retten",
  "das Rezept",
  "die Rezeption",
  "der Richter",
  "richtig",
  "die Richtung",
  "riechen",
  "riesig",
  "das Rind",
  "der Ring",
  "die Reihenfolge",
  "rein",
  "reinigen",
  "die Reinigung",
  "der Reis",
  "reisen",
  "die Reise",
  "das Reisebüro",
  "reiten",
  "die Reklame",
  "der Rekord",
  "relativ",
  "die Religion",
  "rennen",
  "die Rente",
  "der Rentner",
  "reparieren",
  "die Runde",
  "die Rundfahrt",
  "der Saal",
  "die Sache",
  "der Sack",
  "der Saft",
  "sagen",
  "die Saison",
  "der Salat",
  "die Salbe",
  "der Salon",
  "das Salz",
  "salzig",
  "sammeln",
  "sämtliche",
  "der Sand",
  "das Risiko",
  "der Rock",
  "roh",
  "die Rolle",
  "der Roman",
  "die Rose",
  "der Rucksack",
  "die Rückkehr",
  "rückwärts",
  "der Rücken",
  "die Rücksicht",
  "das Rüebli",
  "rufen",
  "die Rufnummer",
  "die Ruhe",
  "ruhig",
  "rund",
  "schauen",
  "zuschauen",
  "das Schaufenster",
  "der Schauspieler",
  "die Scheibe",
  "sich scheiden",
  "die Scheidung",
  "der Schein",
  "scheinen",
  "schenken",
  "die Schere",
  "schicken",
  "schieben",
  "schief",
  "schießen",
  "das Schiff",
  "der Sänger",
  "satt",
  "der Satz",
  "sauber",
  "sauer",
  "die Schachtel",
  "schade",
  "schaden",
  "der Schaden",
  "schädlich",
  "schaffen",
  "schalten",
  "der Schalter",
  "scharf",
  "der Schatten",
  "schätzen",
  "schließlich",
  "schlimm",
  "das Schloss",
  "der Schluss",
  "der Schlüssel",
  "schmal",
  "schmecken",
  "der Schmerz",
  "das Schmerzmittel",
  "schminken",
  "der Schmuck",
  "der Schmutz",
  "schmutzig",
  "verschmutzen",
  "der Schnee",
  "schneien",
  "das Schild",
  "schimpfen",
  "der Schinken",
  "der Schirm",
  "der Schlaf",
  "schlagen",
  "die Schlange",
  "schlank",
  "schlecht",
  "schließen",
  "das Schreiben",
  "schreien",
  "die Schrift",
  "schriftlich",
  "der Schriftsteller",
  "der Schritt",
  "der Schuh",
  "die Schuld",
  "schuld",
  "die Schulden",
  "schuldig",
  "die Schule",
  "die Schularbeit",
  "der Schüler",
  "die Schulter",
  "die Schüssel",
  "schütteln",
  "schützen",
  "schnell",
  "das Schnitzel",
  "der Schnupfen",
  "die Schokolade",
  "schön",
  "der Schrank",
  "der Schreck",
  "schrecklich",
  "schreiben",
  "aufschreiben",
  "die Sehenswürdigkeit",
  "die Seife",
  "sein",
  "seit",
  "seitdem",
  "die Seite",
  "der Sekretär",
  "selb-",
  "selbst",
  "selber",
  "selbstständig",
  "selbstverständlich",
  "der Schutz",
  "schwach",
  "das Schwammerl",
  "die Schwangerschaft",
  "schweigen",
  "schwer",
  "die Schwester",
  "schwierig",
  "die Schwierigkeit",
  "schwimmen",
  "das Schwimmbad",
  "schwitzen",
  "der See",
  "die See",
  "sehen",
  "sichtbar",
  "siegen",
  "der Sieg",
  "der Sieger",
  "singen",
  "sinken",
  "der Sinn",
  "sinnlos",
  "sinnvoll",
  "die Situation",
  "sitzen",
  "der Sitz",
  "der Ski",
  "sobald",
  "selten",
  "seltsam",
  "das Semester",
  "das Seminar",
  "die Semmel",
  "senden",
  "der Sender",
  "die Sendung",
  "die Senioren",
  "senkrecht",
  "die Serie",
  "der Service",
  "der Serviceangestellte",
  "der Sessel",
  "sicher",
  "die Sicherheit",
  "sichern",
  "das Souvenir",
  "soviel",
  "sowieso",
  "sozial",
  "der Sozialarbeiter",
  "spannend",
  "sparen",
  "sparsam",
  "der Spaß",
  "spät",
  "spätestens",
  "der Spaziergang",
  "speichern",
  "die Socke",
  "sodass",
  "das Sofa",
  "sofort",
  "sogenannt-",
  "sogar",
  "der Sohn",
  "solange",
  "solch-",
  "sollen",
  "sondern",
  "die Sonne",
  "sonnig",
  "sonst",
  "sorgen",
  "die Sorge",
  "die Soße",
  "die Sprechstunde",
  "springen",
  "die Spritze",
  "spülen",
  "die Spur",
  "spüren",
  "das Stadion",
  "die Stadt",
  "städtisch",
  "der Stadtplan",
  "stammen",
  "ständig",
  "der Standpunkt",
  "der Star",
  "stark",
  "starten",
  "die Speisekarte",
  "der Speisewagen",
  "der Spezialist",
  "speziell",
  "der Spiegel",
  "spielen",
  "das Spiel",
  "der Spieler",
  "der Spielplatz",
  "das Spielzeug",
  "spitz",
  "der Sport",
  "die Sportart",
  "der Sportler",
  "sportlich",
  "die Sprache",
  "die Fremdsprache",
  "die Muttersprache",
  "die Zweitsprache",
  "sprechen",
  "steil",
  "der Stein",
  "die Stelle",
  "stellen",
  "der Stempel",
  "sterben",
  "der Stern",
  "die Steuer",
  "der Steward",
  "der Stift",
  "der Stil",
  "stilistisch",
  "still",
  "der Stiefel",
  "die Stiege",
  "das Stiegenhaus",
  "der Start",
  "die Station",
  "die Statistik",
  "statistisch",
  "statt",
  "stattfinden",
  "der Stau",
  "der Staub",
  "staubsaugen",
  "stechen",
  "stecken",
  "die Steckdose",
  "der Stecker",
  "stehen",
  "stehlen",
  "steigen",
  "das Streichholz",
  "streiken",
  "der Streik",
  "der Streit",
  "streng",
  "der Stress",
  "der Strom",
  "der Strumpf",
  "das Stück",
  "die Studie",
  "studieren",
  "der Student",
  "der Studierende",
  "das Studium",
  "das Studio",
  "die Stufe",
  "der Stuhl",
  "stumm",
  "die Stimme",
  "stimmen",
  "die Stimmung",
  "stinken",
  "der Stock",
  "das Stockwerk",
  "der Stoff",
  "stolz",
  "stoppen",
  "stören",
  "die Störung",
  "die Strafe",
  "strafbar",
  "der Strafzettel",
  "der Strand",
  "die Straße",
  "die Strecke",
  "die Tabelle",
  "die Tablette",
  "die Tafel",
  "der Tagesablauf",
  "das Tal",
  "das Talent",
  "tanken",
  "die Tankstelle",
  "die Tante",
  "tanzen",
  "der Tanz",
  "die Tasche",
  "das Taschengeld",
  "das Taschentuch",
  "die Tasse",
  "die Tastatur",
  "die Taste",
  "die Tat",
  "der Täter",
  "die Tätigkeit",
  "die Stunde",
  "der Sturm",
  "stürzen",
  "suchen",
  "die Sucht",
  "süchtig",
  "das Suchtmittel",
  "die Summe",
  "super",
  "der Supermarkt",
  "die Suppe",
  "süß",
  "das Symbol",
  "sympathisch",
  "das System",
  "die Szene",
  "das Telefon",
  "die Temperatur",
  "das Tempo",
  "das Tennis",
  "der Teppich",
  "der Termin",
  "der Terminkalender",
  "die Terrasse",
  "testen",
  "der Test",
  "teuer",
  "der Text",
  "das Theater",
  "das Thema",
  "theoretisch",
  "die Theorie",
  "die Therapie",
  "das Ticket",
  "tief",
  "das Tier",
  "die Tatsache",
  "tatsächlich",
  "taub",
  "tauchen",
  "tauschen",
  "die Technik",
  "technisch",
  "die Technologie",
  "der Tee",
  "teilen",
  "das Teil",
  "der Teil",
  "die Teilzeit",
  "teilnehmen",
  "die Teilnahme",
  "der Teilnehmer",
  "telefonieren",
  "die Tradition",
  "traditionell",
  "tragen",
  "trainieren",
  "der Trainer",
  "das Training",
  "das Tram",
  "die Träne",
  "der Transport",
  "träumen",
  "der Traum",
  "traurig",
  "treffen",
  "der Treffpunkt",
  "treiben",
  "die Trennung",
  "das Haustier",
  "der Tierpark",
  "der Tipp",
  "tippen",
  "der Tisch",
  "der Titel",
  "die Tochter",
  "der Tod",
  "tödlich",
  "die Toilette",
  "tolerant",
  "toll",
  "die Tomate",
  "der Topf",
  "das Tor",
  "die Torte",
  "tot",
  "der Tote",
  "total",
  "der Tourismus",
  "der Tourist",
  "die Tüte",
  "der Typ",
  "typisch",
  "üben",
  "die Übung",
  "über",
  "überall",
  "überfahren",
  "überhaupt",
  "überholen",
  "überlegen",
  "die Treppe",
  "das Treppenhaus",
  "treten",
  "treu",
  "trinken",
  "das Trinkgeld",
  "trocken",
  "trocknen",
  "die Tropfen",
  "das Trottoir",
  "trotz",
  "trotzdem",
  "das Tuch",
  "tun",
  "die Tür",
  "der Turm",
  "üblich",
  "übrig",
  "übrigens",
  "das Ufer",
  "die Uhr",
  "umarmen",
  "die Umfrage",
  "die Umgebung",
  "umgehen",
  "umgekehrt",
  "die Umleitung",
  "umso",
  "umsonst",
  "übermorgen",
  "übernachten",
  "die Übernachtung",
  "übernehmen",
  "überprüfen",
  "überqueren",
  "überraschen",
  "die Überraschung",
  "überreden",
  "die Überschrift",
  "übersetzen",
  "der Übersetzer",
  "die Übersetzung",
  "die Überstunde",
  "überweisen",
  "die Überweisung",
  "die Uniform",
  "die Universität",
  "unter",
  "unter-",
  "unterbrechen",
  "die Unterhaltung",
  "die Unterkunft",
  "die Unterlagen",
  "unterlassen",
  "unternehmen",
  "der Unternehmer",
  "unterrichten",
  "der Unterricht",
  "untersagt",
  "unterscheiden",
  "der Unterschied",
  "umsteigen",
  "umtauschen",
  "der Umtausch",
  "die Umwelt",
  "der Umweltschutz",
  "die Umweltver-",
  "umziehen",
  "der Umzug",
  "sich umziehen",
  "un-",
  "unbedingt",
  "der Unfall",
  "ungefähr",
  "ungewöhnlich",
  "unglaublich",
  "das Unglück",
  "unheimlich",
  "die Vase",
  "der Vater",
  "vegetarisch",
  "das Velo",
  "verabredet",
  "die Verabredung",
  "der Abschied",
  "die Veranstaltung",
  "verantwortlich",
  "die Verantwortung",
  "verbieten",
  "das Verbot",
  "verboten",
  "verbinden",
  "unterschiedlich",
  "unterschreiben",
  "die Unterschrift",
  "unterstreichen",
  "unterstützen",
  "die Unterstützung",
  "untersuchen",
  "die Untersuchung",
  "unterwegs",
  "die Urkunde",
  "der Urlaub",
  "die Ursache",
  "verursachen",
  "ursprünglich",
  "das Urteil",
  "das Vergnügen",
  "vergnügt",
  "vergrößern",
  "verhaften",
  "sich verhalten",
  "das Verhalten",
  "das Verhältnis",
  "verheiratet",
  "verhindern",
  "verkaufen",
  "der Verkäufer",
  "der Verkehr",
  "das Verkehrsmittel",
  "der Verlag",
  "verlangen",
  "verlängern",
  "verlassen",
  "die Verbindung",
  "verbrauchen",
  "der Verbrecher",
  "verbringen",
  "der Verdacht",
  "verdächtig",
  "verdienen",
  "der Verein",
  "vereinbaren",
  "die Vergangenheit",
  "vergeblich",
  "vergessen",
  "vergleichen",
  "der Vergleich",
  "sich vergnügen",
  "verpflegen",
  "verpflichtet",
  "verraten",
  "verreisen",
  "verrückt",
  "die Versammlung",
  "versäumen",
  "verschieben",
  "verschieden",
  "verschreiben",
  "verschwinden",
  "versichern",
  "die Versichertenkarte",
  "die Versicherung",
  "die Verspätung",
  "versprechen",
  "verständlich",
  "sich verlaufen",
  "die Verletzung",
  "sich verlieben",
  "verliebt",
  "verlieren",
  "der Verlierer",
  "der Verlust",
  "vermeiden",
  "vermieten",
  "der Vermieter",
  "die Vermietung",
  "vermissen",
  "die Vermittlung",
  "vermuten",
  "vermutlich",
  "vernünftig",
  "verpacken",
  "verpassen",
  "verwenden",
  "verzeihen",
  "verzichten",
  "das Video",
  "vielleicht",
  "das Viertel",
  "virtuell",
  "der Virus",
  "die Visitenkarte",
  "das Visum",
  "das Vitamin",
  "voll",
  "die Vollzeit",
  "völlig",
  "von",
  "das Verständnis",
  "versuchen",
  "der Versuch",
  "verteilen",
  "der Vertrag",
  "vertrauen",
  "das Vertrauen",
  "vertreten",
  "der Vertreter",
  "die Vertretung",
  "verurteilen",
  "die Verwaltung",
  "verwandt",
  "der Verwandte",
  "verwechseln",
  "vorläufig",
  "vorlesen",
  "vorn",
  "vorschlagen",
  "der Vorschlag",
  "die Vorschrift",
  "die Vorsicht",
  "vorsichtig",
  "die Vorstellung",
  "das Vorstellungsgespräch",
  "der Vorteil",
  "der Vortrag",
  "die Vorwahl",
  "vorwärts",
  "der Vorwurf",
  "voneinander",
  "vor",
  "voraus",
  "die Voraussetzung",
  "voraussichtlich",
  "die Vorbereitung",
  "vorder-",
  "die Vorfahrt",
  "vorgestern",
  "vorhaben",
  "vorher",
  "vorhin",
  "vorkommen",
  "wann",
  "die Ware",
  "warm",
  "die Wärme",
  "warnen",
  "warten",
  "warum",
  "was",
  "die Wäsche",
  "das Waschmittel",
  "das Wasser",
  "wechseln",
  "wecken",
  "der Wecker",
  "waagerecht",
  "wach",
  "wachsen",
  "der Wagen",
  "wählen",
  "die Wahl",
  "wahnsinnig",
  "wahr",
  "die Wahrheit",
  "während",
  "wahrscheinlich",
  "der Wald",
  "die Wand",
  "wandern",
  "die Wanderung",
  "weltweit",
  "wenden",
  "wenigstens",
  "wenn",
  "wer",
  "die Werbung",
  "werden",
  "werfen",
  "das Werk",
  "die Werkstatt",
  "das Werkzeug",
  "wert",
  "der Wert",
  "wertlos",
  "wertvoll",
  "weshalb",
  "der Weg",
  "wegen",
  "wehtun",
  "weiblich",
  "weich",
  "sich weigern",
  "weil",
  "der Wein",
  "weinen",
  "weit",
  "die Weiterbildung",
  "welcher",
  "die Welt",
  "willkommen",
  "der Wind",
  "windig",
  "winken",
  "wirken",
  "die Wirkung",
  "wirklich",
  "die Wirklichkeit",
  "der Wirt",
  "die Wirtschaft",
  "wissen",
  "das Wissen",
  "die Wissenschaft",
  "der Wissenschaftler",
  "der Witz",
  "woher",
  "wohin",
  "der Wettbewerb",
  "wetten",
  "das Wetter",
  "der Wetterbericht",
  "die Wettervorhersage",
  "wichtig",
  "widersprechen",
  "wie",
  "wiederholen",
  "die Wiederholung",
  "wiegen",
  "wild",
  "die Wiese",
  "wieso",
  "wunderschön",
  "sich wundern",
  "der Wunsch",
  "die Wurst",
  "wütend",
  "die Zahl",
  "die Anzahl",
  "zahlreich",
  "zahlen",
  "die Zahlung",
  "zählen",
  "der Zahn",
  "die Zahncreme",
  "die Zange",
  "das Zeichen",
  "wohl",
  "wohnen",
  "der Wohnsitz",
  "die Wohnung",
  "das Wohnzimmer",
  "die Wolke",
  "bewölkt",
  "die Wolle",
  "wollen",
  "worüber",
  "worum",
  "das Wort",
  "das Wörterbuch",
  "die Wunde",
  "das Wunder",
  "wunderbar",
  "das Zeugnis",
  "ziehen",
  "das Ziel",
  "ziemlich",
  "die Zigarette",
  "das Zimmer",
  "die Zinsen",
  "der Zirkus",
  "die Zitrone",
  "der Zivilstand",
  "der Zoll",
  "die Zone",
  "der Zoo",
  "zubereiten",
  "der Zucker",
  "das Verkehrszeichen",
  "zeichnen",
  "die Zeichnung",
  "zeigen",
  "die Zeile",
  "die Zeit",
  "der Zeitpunkt",
  "zurzeit",
  "die Zeitschrift",
  "die Zeitung",
  "das Zelt",
  "zelten",
  "zentral",
  "das Zentrum",
  "zerstören",
  "das Zertifikat",
  "der Zettel",
  "das Zeug",
  "der Zeuge",
  "die Zünder",
  "das Zündholz",
  "zunehmen",
  "zurechtkommen",
  "zusagen",
  "die Zusammenarbeit",
  "zusammenfassen",
  "der Zusammenhang",
  "zusätzlich",
  "der Zuschauer",
  "der Zuschlag",
  "zuerst",
  "der Zufall",
  "zufällig",
  "zufrieden",
  "der Zugang",
  "zugänglich",
  "der Zug",
  "zugehen",
  "das Zuhause",
  "zuhören",
  "der Zuhörer",
  "die Zukunft",
  "zukünftig",
  "zuletzt",
  "zumachen",
  "zumindest",
  "zunächst",
  "der Zweck",
  "zweifeln",
  "der Zweifel",
  "die Zwiebel",
  "zwischen",
  "der Zustand",
  "zuständig",
  "zustimmen",
  "die Zustimmung",
  "die Zutaten",
  "zuverlässig",
  "zwar"
];

async function generateVocabBatch(words) {
  const prompt = `请为以下德语B1词汇生成学习数据，严格按JSON数组格式返回，不要任何其他文字：

词汇：${words.join(', ')}

每个词格式：
{
  "word": "完整词形（名词带冠词，动词原形）",
  "type": "词性（der/die/das/verb/adjektiv/adverb/plural）",
  "meaning_zh": "中文释义",
  "meaning_en": "English meaning",
  "collocation": "最常用搭配（1-2个）",
  "example_de": "德语例句（B1级别，简短）",
  "example_zh": "例句中文翻译",
  "example_en": "English translation",
  "topic": "主题（Arbeit/Familie/Gesundheit/Verkehr/Alltag/Bildung/Freizeit/Kommunikation/Natur/Finanzen/Reise/Wohnen/Medien之一）",
  "frequency": "高/中/低"
}

只返回JSON数组。`;

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${API_KEY}`
    },
    body: JSON.stringify({
      model: 'gpt-4o-mini',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.3,
      max_tokens: 4000
    })
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`API错误 ${response.status}: ${err}`);
  }

  const data = await response.json();
  const text = data.choices[0].message.content.trim();
  const jsonMatch = text.match(/\[[\s\S]*\]/);
  if (!jsonMatch) throw new Error('无法解析JSON');
  return JSON.parse(jsonMatch[0]);
}

async function main() {
  const BATCH_SIZE = 15;
  const progressFile = './vocab_progress.json';
  const outputDir = './src/data';
  
  let results = [];
  let startBatch = 0;

  // 断点续传
  if (fs.existsSync(progressFile)) {
    const progress = JSON.parse(fs.readFileSync(progressFile, 'utf-8'));
    results = progress.results;
    startBatch = progress.nextBatch;
    console.log(`📂 继续上次进度，已完成 ${results.length} 词，从第 ${startBatch + 1} 批继续\n`);
  }

  const totalBatches = Math.ceil(WORD_LIST.length / BATCH_SIZE);
  console.log(`🚀 共 ${WORD_LIST.length} 个词，每批 ${BATCH_SIZE} 个，共 ${totalBatches} 批`);
  console.log(`💰 使用 gpt-4o-mini，预计费用 < $2\n`);

  for (let i = startBatch; i < totalBatches; i++) {
    const batch = WORD_LIST.slice(i * BATCH_SIZE, (i + 1) * BATCH_SIZE);
    const percent = Math.round((i / totalBatches) * 100);
    process.stdout.write(`[${percent}%] 第 ${i+1}/${totalBatches} 批: ${batch[0]}... `);

    let success = false;
    for (let retry = 0; retry < 3; retry++) {
      try {
        const batchResults = await generateVocabBatch(batch);
        batchResults.forEach((item, idx) => { item.id = results.length + idx + 1; });
        results.push(...batchResults);
        console.log(`✅ (${results.length} 词)`);
        success = true;
        break;
      } catch (err) {
        if (retry < 2) {
          process.stdout.write(`重试... `);
          await new Promise(r => setTimeout(r, 2000));
        } else {
          console.log(`❌ 跳过: ${err.message.slice(0, 50)}`);
        }
      }
    }

    // 每批保存进度
    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });
    fs.writeFileSync(progressFile, JSON.stringify({ nextBatch: i + 1, results }, null, 2));
    
    // 每5批保存一次最终文件（方便随时查看进度）
    if (i % 5 === 0) {
      fs.writeFileSync(path.join(outputDir, 'vocab_complete.json'), JSON.stringify(results, null, 2));
    }

    // 避免限流
    await new Promise(r => setTimeout(r, 800));
  }

  // 保存最终结果
  fs.writeFileSync(path.join(outputDir, 'vocab_complete.json'), JSON.stringify(results, null, 2));
  if (fs.existsSync(progressFile)) fs.unlinkSync(progressFile);
  
  console.log(`\n🎉 全部完成！共 ${results.length} 个词汇`);
  console.log(`📁 已保存到 src/data/vocab_complete.json`);
}

main().catch(console.error);
